module.exports = class Data1791465864099 {
    name = 'Data1791465864099'

    async up(db) {
        await db.query(`CREATE TABLE "owner" ("id" character varying NOT NULL, "address" bytea, "event_name" text NOT NULL, "timestamp" numeric NOT NULL, "created_at" numeric NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "transaction_hash" text NOT NULL, "parcel_id" character varying, "estate_id" character varying, CONSTRAINT "PK_8e86b6b9f94aece7d12d465dc0c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_owner_parcel_693a8b0d" ON "owner" ("parcel_id") `)
        await db.query(`CREATE INDEX "idx_owner_estate_8d2ce63c" ON "owner" ("estate_id") `)
        await db.query(`CREATE TABLE "operator" ("id" character varying NOT NULL, "address" bytea, "event_name" text NOT NULL, "timestamp" numeric NOT NULL, "created_at" numeric NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "transaction_hash" text NOT NULL, "parcel_id" character varying, "estate_id" character varying, CONSTRAINT "PK_8b950e1572745d9f69be7748ae8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_operator_parcel_3e4e0701" ON "operator" ("parcel_id") `)
        await db.query(`CREATE INDEX "idx_operator_estate_256ff686" ON "operator" ("estate_id") `)
        await db.query(`CREATE TABLE "update_operator" ("id" character varying NOT NULL, "address" bytea, "event_name" text NOT NULL, "timestamp" numeric NOT NULL, "created_at" numeric NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "transaction_hash" text NOT NULL, "parcel_id" character varying, "estate_id" character varying, CONSTRAINT "PK_3eb7ecba35ea471088fe3bcd21e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_update_operator_parcel_f1eec062" ON "update_operator" ("parcel_id") `)
        await db.query(`CREATE INDEX "idx_update_operator_estate_c135ebd8" ON "update_operator" ("estate_id") `)
        await db.query(`CREATE TABLE "data" ("id" character varying NOT NULL, "version" text NOT NULL, "name" text, "description" text, "ipns" text, CONSTRAINT "PK_2533602bd9247937e3a4861e173" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "estate" ("id" character varying NOT NULL, "operator" bytea, "update_operator" bytea, "size" integer, "created_at" numeric, "updated_at" numeric, "owner_id" character varying, "data_id" character varying, CONSTRAINT "REL_c40a1b5f5b764ad6ab5fa749cd" UNIQUE ("data_id"), CONSTRAINT "PK_cbb82b5600918dca1140ff8d276" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_estate_owner_30058568" ON "estate" ("owner_id") `)
        await db.query(`CREATE INDEX "idx_estate_update_operator_b588af2f" ON "estate" ("update_operator") `)
        await db.query(`CREATE UNIQUE INDEX "idx_estate_data_8621a487" ON "estate" ("data_id") `)
        await db.query(`CREATE TABLE "wallet" ("id" character varying NOT NULL, "address" bytea NOT NULL, CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "estate_history" ("id" character varying NOT NULL, "prev_estate_id" text, "estate_id" text, "created_at" numeric NOT NULL, "estate_token_id" text NOT NULL, "event_name" text NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "transaction_hash" text NOT NULL, "parcel_id" character varying, CONSTRAINT "PK_e789135ec199ebfed1b4a9bb7d6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_estate_history_estate_id_462e1c5e" ON "estate_history" ("estate_id") `)
        await db.query(`CREATE INDEX "idx_estate_history_parcel_4e6380b8" ON "estate_history" ("parcel_id") `)
        await db.query(`CREATE INDEX "idx_estate_history_estate_token_id_463be587" ON "estate_history" ("estate_token_id") `)
        await db.query(`CREATE INDEX "idx_estate_history_block_number_659ed9e6" ON "estate_history" ("block_number") `)
        await db.query(`CREATE TABLE "parcel" ("id" character varying NOT NULL, "token_id" numeric NOT NULL, "x" numeric NOT NULL, "y" numeric NOT NULL, "operator" bytea, "update_operator" bytea, "updated_at" numeric, "owner_id" character varying, "estate_id" character varying, "data_id" character varying, CONSTRAINT "REL_04ab2b996d659d2f86dbcee860" UNIQUE ("data_id"), CONSTRAINT "PK_c01e9fed31b7433a00942d506b1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_parcel_token_id_2b9a60e5" ON "parcel" ("token_id") `)
        await db.query(`CREATE INDEX "idx_parcel_owner_a16bdd5f" ON "parcel" ("owner_id") `)
        await db.query(`CREATE INDEX "idx_parcel_update_operator_564410bc" ON "parcel" ("update_operator") `)
        await db.query(`CREATE INDEX "idx_parcel_estate_e45d93f0" ON "parcel" ("estate_id") `)
        await db.query(`CREATE UNIQUE INDEX "idx_parcel_data_020cfde4" ON "parcel" ("data_id") `)
        await db.query(`CREATE INDEX "idx_parcel_x_y_42af7888" ON "parcel" ("x", "y") `)
        await db.query(`CREATE TABLE "authorization" ("id" character varying NOT NULL, "type" text NOT NULL, "token_address" bytea NOT NULL, "operator" bytea NOT NULL, "is_approved" boolean NOT NULL, "timestamp" numeric NOT NULL, "created_at" numeric NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "transaction_hash" text NOT NULL, "owner_id" character varying, CONSTRAINT "PK_a8a47afd6ac0d056caccc1e9d22" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_authorization_operator_bca26b5d" ON "authorization" ("operator") `)
        await db.query(`CREATE INDEX "idx_authorization_owner_type_b807efb4" ON "authorization" ("owner_id", "type") `)
        await db.query(`CREATE TABLE "authorization_state" ("id" character varying NOT NULL, "type" text NOT NULL, "token_address" bytea NOT NULL, "operator" bytea NOT NULL, "is_approved" boolean NOT NULL, "timestamp" numeric NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "owner_id" character varying, CONSTRAINT "PK_862f0a7d0d096895f8366287b7a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_authorization_state_operator_7bbcf1b8" ON "authorization_state" ("operator") `)
        await db.query(`CREATE INDEX "idx_authorization_state_owner_type_f9979f82" ON "authorization_state" ("owner_id", "type") `)
        await db.query(`CREATE TABLE "rental" ("id" character varying NOT NULL, "contract_address" text NOT NULL, "token_id" numeric NOT NULL, "lessor" text NOT NULL, "tenant" text NOT NULL, "operator" text NOT NULL, "rental_days" numeric NOT NULL, "started_at" numeric NOT NULL, "ends_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "price_per_day" numeric NOT NULL, "sender" text NOT NULL, "owner_has_claimed_asset" boolean NOT NULL, "claimed_at" numeric, "is_extension" boolean NOT NULL, "is_active" boolean NOT NULL, "signature" text NOT NULL, "rental_contract_address" text NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_a20fc571eb61d5a30d8c16d51e8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_rental_contract_address_3d56a3e3" ON "rental" ("contract_address") `)
        await db.query(`CREATE INDEX "idx_rental_token_id_bf3e246c" ON "rental" ("token_id") `)
        await db.query(`CREATE INDEX "idx_rental_lessor_92effc0e" ON "rental" ("lessor") `)
        await db.query(`CREATE INDEX "idx_rental_tenant_d44886f9" ON "rental" ("tenant") `)
        await db.query(`CREATE INDEX "idx_rental_started_at_5918f9fc" ON "rental" ("started_at") `)
        await db.query(`CREATE INDEX "idx_rental_ends_at_46f910ef" ON "rental" ("ends_at") `)
        await db.query(`CREATE INDEX "idx_rental_updated_at_a469c81a" ON "rental" ("updated_at") `)
        await db.query(`CREATE INDEX "idx_rental_is_active_030735ed" ON "rental" ("is_active") `)
        await db.query(`CREATE TABLE "rentals_count" ("id" character varying NOT NULL, "value" numeric NOT NULL, CONSTRAINT "PK_c4dfd901230642233f8ed901ebc" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "indexes_update_contract_history" ("id" character varying NOT NULL, "new_index" numeric NOT NULL, "contract_address" bytea NOT NULL, CONSTRAINT "PK_9281e03235f1e57d17e42839c5a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "indexes_update_signer_history" ("id" character varying NOT NULL, "new_index" numeric NOT NULL, "signer" text NOT NULL, CONSTRAINT "PK_ba10c371e35b239c0b37f015a47" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_indexes_update_signer_history_signer_3f0f1d75" ON "indexes_update_signer_history" ("signer") `)
        await db.query(`CREATE TABLE "indexes_update_asset_history" ("id" character varying NOT NULL, "new_index" numeric NOT NULL, "signer" text NOT NULL, "token_id" numeric NOT NULL, "contract_address" text NOT NULL, "type" character varying(6) NOT NULL, CONSTRAINT "PK_b9772d03e6448341585414d258a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_indexes_update_asset_history_signer_d807a727" ON "indexes_update_asset_history" ("signer") `)
        await db.query(`CREATE TABLE "indexes_update_history" ("id" character varying NOT NULL, "type" character varying(8) NOT NULL, "date" numeric NOT NULL, "sender" text NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "transaction_hash" text NOT NULL, "contract_update_id" character varying, "singer_update_id" character varying, "asset_update_id" character varying, CONSTRAINT "PK_b08a6d0d2597b18252c9632e870" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_indexes_update_history_date_78665e18" ON "indexes_update_history" ("date") `)
        await db.query(`CREATE INDEX "idx_indexes_update_history_contract_update_80ab8217" ON "indexes_update_history" ("contract_update_id") `)
        await db.query(`CREATE INDEX "idx_indexes_update_history_singer_update_fc4958dc" ON "indexes_update_history" ("singer_update_id") `)
        await db.query(`CREATE INDEX "idx_indexes_update_history_asset_update_fa135478" ON "indexes_update_history" ("asset_update_id") `)
        await db.query(`CREATE TABLE "rentable" ("id" character varying NOT NULL, CONSTRAINT "PK_ae7306d6fc18b1eb136ad3cd9a0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "rental_asset" ("id" character varying NOT NULL, "contract_address" bytea NOT NULL, "token_id" numeric NOT NULL, "lessor" bytea, "is_claimed" boolean NOT NULL, "claimed_at" numeric, CONSTRAINT "PK_c566ee8894fe074f4c5daeab93a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_rental_asset_lessor_d9d32e97" ON "rental_asset" ("lessor") `)
        await db.query(`CREATE TABLE "rentals_contract" ("id" character varying NOT NULL, "fee" numeric NOT NULL, CONSTRAINT "PK_aeb6a9105e7188f994c16d106fe" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "analytics_total_data" ("id" character varying NOT NULL, "rentals" integer NOT NULL, "volume" numeric NOT NULL, "lessor_earnings" numeric NOT NULL, "fee_collector_earnings" numeric NOT NULL, CONSTRAINT "PK_50026a19b75884db3207bac9620" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "analytics_day_data" ("id" character varying NOT NULL, "date" integer NOT NULL, "rentals" integer NOT NULL, "volume" numeric NOT NULL, "lessor_earnings" numeric NOT NULL, "fee_collector_earnings" numeric NOT NULL, CONSTRAINT "PK_0f692899aeae43f1c1596430ea8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "third_party_metadata" ("id" character varying NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "contracts" jsonb, CONSTRAINT "PK_5a8f9a84a82c9f0fe6c688a4e0d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "metadata" ("id" character varying NOT NULL, "type" character varying(14) NOT NULL, "third_party_id" character varying, CONSTRAINT "PK_56b22355e89941b9792c04ab176" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_metadata_third_party_909760c1" ON "metadata" ("third_party_id") `)
        await db.query(`CREATE TABLE "third_party_root_history" ("id" character varying NOT NULL, "root" text NOT NULL, "is_approved" boolean NOT NULL, "event_name" text NOT NULL, "block_number" integer NOT NULL, "log_index" integer NOT NULL, "timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "third_party_id" character varying, CONSTRAINT "PK_f94bd7fed2f7bd31afef6ae1948" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_third_party_root_history_third_party_block_number_6734f344" ON "third_party_root_history" ("third_party_id", "block_number") `)
        await db.query(`CREATE TABLE "third_party" ("id" character varying NOT NULL, "managers" text array NOT NULL, "raw_metadata" text NOT NULL, "resolver" text, "is_approved" boolean, "max_items" numeric NOT NULL, "root" text NOT NULL, "consumed_slots" numeric NOT NULL, "is_programmatic" boolean NOT NULL, "search_name" text, "search_description" text, "search_text" text, "metadata_id" character varying, CONSTRAINT "PK_a9b4c282f25d91ea8a5493929df" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_third_party_is_approved_f8a8d734" ON "third_party" ("is_approved") `)
        await db.query(`CREATE INDEX "idx_third_party_metadata_992038b6" ON "third_party" ("metadata_id") `)
        await db.query(`CREATE TABLE "receipt" ("id" character varying NOT NULL, "qty" numeric NOT NULL, "signer" text NOT NULL, "created_at" numeric NOT NULL, "third_party_id" character varying, "curation_id" character varying, CONSTRAINT "PK_b4b9ec7d164235fbba023da9832" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_receipt_third_party_0ca1534d" ON "receipt" ("third_party_id") `)
        await db.query(`CREATE INDEX "idx_receipt_curation_36dc0efc" ON "receipt" ("curation_id") `)
        await db.query(`CREATE TABLE "curation" ("id" character varying NOT NULL, "qty" numeric NOT NULL, CONSTRAINT "PK_de0e4d1c645b4bc2e9a26b9a3f1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "linked_contracts" ("id" character varying NOT NULL, "network" text NOT NULL, "address" text NOT NULL, CONSTRAINT "PK_c378683f9b2672324a3159ba8d0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "registry_data" ("id" character varying NOT NULL, "aggregator_address" text NOT NULL, CONSTRAINT "PK_9fad63ce905a1f4462ab07365b7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "third_party_count" ("id" character varying NOT NULL, "third_party_total" numeric NOT NULL, "receipt_total" numeric NOT NULL, "curation_total" numeric NOT NULL, CONSTRAINT "PK_f4a0d535d3782fd895d238dc8ea" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "owner" ADD CONSTRAINT "FK_3de1edac4f3c91be98c59970535" FOREIGN KEY ("parcel_id") REFERENCES "parcel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "owner" ADD CONSTRAINT "FK_96403d79f7bd539fdc6d7fb7aaa" FOREIGN KEY ("estate_id") REFERENCES "estate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "operator" ADD CONSTRAINT "FK_787ded7a2f08ae377602d5e2c33" FOREIGN KEY ("parcel_id") REFERENCES "parcel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "operator" ADD CONSTRAINT "FK_03325f53caba37ca7c3e374649b" FOREIGN KEY ("estate_id") REFERENCES "estate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "update_operator" ADD CONSTRAINT "FK_81664e0cc588618d1bf216b996a" FOREIGN KEY ("parcel_id") REFERENCES "parcel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "update_operator" ADD CONSTRAINT "FK_f0f008fb9d45ec1ce9b71498658" FOREIGN KEY ("estate_id") REFERENCES "estate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "estate" ADD CONSTRAINT "FK_0b680d37990796da3232ad9d98c" FOREIGN KEY ("owner_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "estate" ADD CONSTRAINT "FK_c40a1b5f5b764ad6ab5fa749cd2" FOREIGN KEY ("data_id") REFERENCES "data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "estate_history" ADD CONSTRAINT "FK_f27524723acfd82b64a08ea8069" FOREIGN KEY ("parcel_id") REFERENCES "parcel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "parcel" ADD CONSTRAINT "FK_a7c5c87cd4ffc1e1129f0c5f430" FOREIGN KEY ("owner_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "parcel" ADD CONSTRAINT "FK_da4912d77606dcfabe5da7eebc6" FOREIGN KEY ("estate_id") REFERENCES "estate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "parcel" ADD CONSTRAINT "FK_04ab2b996d659d2f86dbcee8606" FOREIGN KEY ("data_id") REFERENCES "data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "authorization" ADD CONSTRAINT "FK_dce3c593e0462f8af994d905f51" FOREIGN KEY ("owner_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "authorization_state" ADD CONSTRAINT "FK_3bf75c014b8da655a5c7c91cb86" FOREIGN KEY ("owner_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "indexes_update_history" ADD CONSTRAINT "FK_3880015bc3f44d1598c76acbe38" FOREIGN KEY ("contract_update_id") REFERENCES "indexes_update_contract_history"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "indexes_update_history" ADD CONSTRAINT "FK_e54bff389cbdff75376cf3c6f49" FOREIGN KEY ("singer_update_id") REFERENCES "indexes_update_signer_history"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "indexes_update_history" ADD CONSTRAINT "FK_bcaf7ce47d56fddbc81a89a47ab" FOREIGN KEY ("asset_update_id") REFERENCES "indexes_update_asset_history"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_73095d0fde3e8fe285ffe78d0ff" FOREIGN KEY ("third_party_id") REFERENCES "third_party_metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "third_party_root_history" ADD CONSTRAINT "FK_bf3c02d135868c5243aa8028a40" FOREIGN KEY ("third_party_id") REFERENCES "third_party"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "third_party" ADD CONSTRAINT "FK_5a8f9a84a82c9f0fe6c688a4e0d" FOREIGN KEY ("metadata_id") REFERENCES "metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "receipt" ADD CONSTRAINT "FK_8889daf7f2d783ba83d57b21501" FOREIGN KEY ("third_party_id") REFERENCES "third_party"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "receipt" ADD CONSTRAINT "FK_d2ccfa6261a23cb7d6d9b532225" FOREIGN KEY ("curation_id") REFERENCES "curation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "receipt" DROP CONSTRAINT "FK_d2ccfa6261a23cb7d6d9b532225"`)
        await db.query(`ALTER TABLE "receipt" DROP CONSTRAINT "FK_8889daf7f2d783ba83d57b21501"`)
        await db.query(`ALTER TABLE "third_party" DROP CONSTRAINT "FK_5a8f9a84a82c9f0fe6c688a4e0d"`)
        await db.query(`ALTER TABLE "third_party_root_history" DROP CONSTRAINT "FK_bf3c02d135868c5243aa8028a40"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_73095d0fde3e8fe285ffe78d0ff"`)
        await db.query(`ALTER TABLE "indexes_update_history" DROP CONSTRAINT "FK_bcaf7ce47d56fddbc81a89a47ab"`)
        await db.query(`ALTER TABLE "indexes_update_history" DROP CONSTRAINT "FK_e54bff389cbdff75376cf3c6f49"`)
        await db.query(`ALTER TABLE "indexes_update_history" DROP CONSTRAINT "FK_3880015bc3f44d1598c76acbe38"`)
        await db.query(`ALTER TABLE "authorization_state" DROP CONSTRAINT "FK_3bf75c014b8da655a5c7c91cb86"`)
        await db.query(`ALTER TABLE "authorization" DROP CONSTRAINT "FK_dce3c593e0462f8af994d905f51"`)
        await db.query(`ALTER TABLE "parcel" DROP CONSTRAINT "FK_04ab2b996d659d2f86dbcee8606"`)
        await db.query(`ALTER TABLE "parcel" DROP CONSTRAINT "FK_da4912d77606dcfabe5da7eebc6"`)
        await db.query(`ALTER TABLE "parcel" DROP CONSTRAINT "FK_a7c5c87cd4ffc1e1129f0c5f430"`)
        await db.query(`ALTER TABLE "estate_history" DROP CONSTRAINT "FK_f27524723acfd82b64a08ea8069"`)
        await db.query(`ALTER TABLE "estate" DROP CONSTRAINT "FK_c40a1b5f5b764ad6ab5fa749cd2"`)
        await db.query(`ALTER TABLE "estate" DROP CONSTRAINT "FK_0b680d37990796da3232ad9d98c"`)
        await db.query(`ALTER TABLE "update_operator" DROP CONSTRAINT "FK_f0f008fb9d45ec1ce9b71498658"`)
        await db.query(`ALTER TABLE "update_operator" DROP CONSTRAINT "FK_81664e0cc588618d1bf216b996a"`)
        await db.query(`ALTER TABLE "operator" DROP CONSTRAINT "FK_03325f53caba37ca7c3e374649b"`)
        await db.query(`ALTER TABLE "operator" DROP CONSTRAINT "FK_787ded7a2f08ae377602d5e2c33"`)
        await db.query(`ALTER TABLE "owner" DROP CONSTRAINT "FK_96403d79f7bd539fdc6d7fb7aaa"`)
        await db.query(`ALTER TABLE "owner" DROP CONSTRAINT "FK_3de1edac4f3c91be98c59970535"`)
        await db.query(`DROP TABLE "third_party_count"`)
        await db.query(`DROP TABLE "registry_data"`)
        await db.query(`DROP TABLE "linked_contracts"`)
        await db.query(`DROP TABLE "curation"`)
        await db.query(`DROP INDEX "public"."idx_receipt_curation_36dc0efc"`)
        await db.query(`DROP INDEX "public"."idx_receipt_third_party_0ca1534d"`)
        await db.query(`DROP TABLE "receipt"`)
        await db.query(`DROP INDEX "public"."idx_third_party_metadata_992038b6"`)
        await db.query(`DROP INDEX "public"."idx_third_party_is_approved_f8a8d734"`)
        await db.query(`DROP TABLE "third_party"`)
        await db.query(`DROP INDEX "public"."idx_third_party_root_history_third_party_block_number_6734f344"`)
        await db.query(`DROP TABLE "third_party_root_history"`)
        await db.query(`DROP INDEX "public"."idx_metadata_third_party_909760c1"`)
        await db.query(`DROP TABLE "metadata"`)
        await db.query(`DROP TABLE "third_party_metadata"`)
        await db.query(`DROP TABLE "analytics_day_data"`)
        await db.query(`DROP TABLE "analytics_total_data"`)
        await db.query(`DROP TABLE "rentals_contract"`)
        await db.query(`DROP INDEX "public"."idx_rental_asset_lessor_d9d32e97"`)
        await db.query(`DROP TABLE "rental_asset"`)
        await db.query(`DROP TABLE "rentable"`)
        await db.query(`DROP INDEX "public"."idx_indexes_update_history_asset_update_fa135478"`)
        await db.query(`DROP INDEX "public"."idx_indexes_update_history_singer_update_fc4958dc"`)
        await db.query(`DROP INDEX "public"."idx_indexes_update_history_contract_update_80ab8217"`)
        await db.query(`DROP INDEX "public"."idx_indexes_update_history_date_78665e18"`)
        await db.query(`DROP TABLE "indexes_update_history"`)
        await db.query(`DROP INDEX "public"."idx_indexes_update_asset_history_signer_d807a727"`)
        await db.query(`DROP TABLE "indexes_update_asset_history"`)
        await db.query(`DROP INDEX "public"."idx_indexes_update_signer_history_signer_3f0f1d75"`)
        await db.query(`DROP TABLE "indexes_update_signer_history"`)
        await db.query(`DROP TABLE "indexes_update_contract_history"`)
        await db.query(`DROP TABLE "rentals_count"`)
        await db.query(`DROP INDEX "public"."idx_rental_is_active_030735ed"`)
        await db.query(`DROP INDEX "public"."idx_rental_updated_at_a469c81a"`)
        await db.query(`DROP INDEX "public"."idx_rental_ends_at_46f910ef"`)
        await db.query(`DROP INDEX "public"."idx_rental_started_at_5918f9fc"`)
        await db.query(`DROP INDEX "public"."idx_rental_tenant_d44886f9"`)
        await db.query(`DROP INDEX "public"."idx_rental_lessor_92effc0e"`)
        await db.query(`DROP INDEX "public"."idx_rental_token_id_bf3e246c"`)
        await db.query(`DROP INDEX "public"."idx_rental_contract_address_3d56a3e3"`)
        await db.query(`DROP TABLE "rental"`)
        await db.query(`DROP INDEX "public"."idx_authorization_state_owner_type_f9979f82"`)
        await db.query(`DROP INDEX "public"."idx_authorization_state_operator_7bbcf1b8"`)
        await db.query(`DROP TABLE "authorization_state"`)
        await db.query(`DROP INDEX "public"."idx_authorization_owner_type_b807efb4"`)
        await db.query(`DROP INDEX "public"."idx_authorization_operator_bca26b5d"`)
        await db.query(`DROP TABLE "authorization"`)
        await db.query(`DROP INDEX "public"."idx_parcel_x_y_42af7888"`)
        await db.query(`DROP INDEX "public"."idx_parcel_data_020cfde4"`)
        await db.query(`DROP INDEX "public"."idx_parcel_estate_e45d93f0"`)
        await db.query(`DROP INDEX "public"."idx_parcel_update_operator_564410bc"`)
        await db.query(`DROP INDEX "public"."idx_parcel_owner_a16bdd5f"`)
        await db.query(`DROP INDEX "public"."idx_parcel_token_id_2b9a60e5"`)
        await db.query(`DROP TABLE "parcel"`)
        await db.query(`DROP INDEX "public"."idx_estate_history_block_number_659ed9e6"`)
        await db.query(`DROP INDEX "public"."idx_estate_history_estate_token_id_463be587"`)
        await db.query(`DROP INDEX "public"."idx_estate_history_parcel_4e6380b8"`)
        await db.query(`DROP INDEX "public"."idx_estate_history_estate_id_462e1c5e"`)
        await db.query(`DROP TABLE "estate_history"`)
        await db.query(`DROP TABLE "wallet"`)
        await db.query(`DROP INDEX "public"."idx_estate_data_8621a487"`)
        await db.query(`DROP INDEX "public"."idx_estate_update_operator_b588af2f"`)
        await db.query(`DROP INDEX "public"."idx_estate_owner_30058568"`)
        await db.query(`DROP TABLE "estate"`)
        await db.query(`DROP TABLE "data"`)
        await db.query(`DROP INDEX "public"."idx_update_operator_estate_c135ebd8"`)
        await db.query(`DROP INDEX "public"."idx_update_operator_parcel_f1eec062"`)
        await db.query(`DROP TABLE "update_operator"`)
        await db.query(`DROP INDEX "public"."idx_operator_estate_256ff686"`)
        await db.query(`DROP INDEX "public"."idx_operator_parcel_3e4e0701"`)
        await db.query(`DROP TABLE "operator"`)
        await db.query(`DROP INDEX "public"."idx_owner_estate_8d2ce63c"`)
        await db.query(`DROP INDEX "public"."idx_owner_parcel_693a8b0d"`)
        await db.query(`DROP TABLE "owner"`)
    }
}
